name: 'GESIS Methods Hub Preview'
description: 'Preview content of GitHub repository for GESIS Methods Hub'
inputs:
  file:
    description: 'File to render to HTML'
    required: false
    default: 'README.md'
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        echo jupyter-repo2docker==2024.7.0 > .gesis-methodshub-gh-action-preview.txt
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: pip
        cache-dependency-path: .gesis-methodshub-gh-action-preview.txt
    - shell: bash
      run: python -m pip install -r .gesis-methodshub-gh-action-preview.txt
    - shell: bash
      run: |
        repo2docker \
        --image-name $GITHUB_REPOSITORY_ID:$GITHUB_SHA \
        --no-run \
        --no-push \
        .
    - shell: bash
      env:
        INPUT_FILE: ${{ inputs.file }}
      run: |
        docker \
        run \
        $GITHUB_REPOSITORY_ID:$GITHUB_SHA \
        quarto \
        render \
        $INPUT_FILE \
        --execute \
        --to html
