name: Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test-github-action:
    runs-on: ubuntu-24.04
    name: Test GitHub Action
    steps:
      - uses: ./
        with:
          file: README.md
